### ISSUE TITLE
IE 9 hast someone problems

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#12]
Successes icons are not centered

**Comment by christoph-fricke** [comment]
@quannten24  Looking good in IE 11... Who is even using IE 9? xD

**Comment by bendixsonnenberg** [comment]
@christoph-fricke try out the new branch

**Comment by christoph-fricke** [comment]
@quannten24 We really have to think about IE 9... I mean who the f*ck is using it expect companys, using winXP...
