### ISSUE TITLE
Contact Inputs breaking wrong

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#14]
Reference to commit: https://github.com/christoph-fricke/shpioneers.de/commit/ef2614eaff2f063893c63e608870804faec4d6ac

The width of the 2 field should be exactly 450px (47.5% for each input and 5% for margin between)... However second field will break in a new line... It looks like there si a tiny pixel gap between them but I dont know where it is coming from...

**Comment by bendixsonnenberg** [comment]
calculated the width 
0f06f11e3fb1e5817223442e95c93e63f705777e
