### ISSUE TITLE
date for news

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#20]
how will we generate the date for newsarticles?
i thought we would just let the person add the unixtimecode in the file.
@christoph-fricke

**Comment by christoph-fricke** [comment]
Add don't know.... I thought `unixtimecode` means that a script will generate the time and `unixtimecode` is a definded variable... However after thinking about it... It does not make sence... They have to add it manually.

**Comment by bendixsonnenberg** [comment]
we could write an entire backend so that nobody has to see the code but other than that it will have to be added manually
