### ISSUE TITLE
Moving language in navbar on mobile

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#27]
Thinking about moving the language option in the navbar menu on mobile. It feels out of place in its current position and looks a bit silly when it pops up.

**Comment by bendixsonnenberg** [comment]
where would you propose we put it?

**Comment by christoph-fricke** [comment]
Within in the pop up and then width a little line between them or something like that.

**Comment by christoph-fricke** [comment]
Test run in moved-language

**Comment by christoph-fricke** [comment]
#45 to do it
