### ISSUE TITLE
animation for newsresizing

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#29]
because ive used height auto the height is not animated and therefore the transition looks a bit weird

**Comment by christoph-fricke** [comment]
I rethought the animation and found a problem... How should the floating of the other cards work if we click on the second card for example... I have not found a nice looking way yet other than to abort the current idea.

**Comment by bendixsonnenberg** [comment]
that already works Am 10.03.2017 17:32 schrieb Christoph Fricke <notifications@github.com>:I rethought the animation and found a problem... How should the floating of the other cards work if we click on the second card for example... I have not found a nice looking way yet other than to abort the current idea.

**Comment by christoph-fricke** [comment]
The transformation looks a little bit of and needs some love...

**Comment by christoph-fricke** [comment]
I might look weird because the element is getting class minor first and then selected. Even if it should be a very fast switch, it might cause some glitches...

**Comment by christoph-fricke** [comment]
Well.. No wonder that the animation looks strange if no animation is happening... Increasing the trasition time to 5s for the height changed nothing so I think we are able to say that nothing is happening... xD

**Comment by christoph-fricke** [comment]
We will come back to this after release...

**Comment by bendixsonnenberg** [comment]
Since the competition is over we won't update this repo anymore.
