### ISSUE TITLE
plus icon

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#34]
linus wants us to change the 'learn more' button to a plus icon

**Comment by christoph-fricke** [comment]
**CHANGE DENIED!!!** A plus button is used when the user has the chance to ADD something and not to get some more information. A plus button would be **no good user experience** and I can promise you that you will not find it on any website!

**Comment by bendixsonnenberg** [comment]
i do agree with youi just wanted to add this as an issue so we could say we talked about it
