### ISSUE TITLE
box shadow is clipping

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#36]
![bildschirmfoto vom 2017-03-13 um 21 56 30](https://cloud.githubusercontent.com/assets/25992157/23874958/f9d3ce72-0837-11e7-874e-ab0604047661.png)

**Comment by christoph-fricke** [comment]
I fixed it in commit https://github.com/christoph-fricke/shpioneers.de/commit/9bde5af281c1cdcc59a1852693679ff5a8da37ee
