### ISSUE TITLE
no animation for getting news-cards back to where they belong

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#38]
i think it will always look a bit ridiculus if the cards try to get back to the position they belong to
also i guess it will annoy more people than it will actually improve anything

**Comment by bendixsonnenberg** [comment]
dont mind the emojii

**Comment by christoph-fricke** [comment]
I am not really sure about this... I may be a bit annoying if the animation takes like for ever... But if the is no animation at all it fells a little bit of and not really like it is material... Maybe a quick animation?

**Comment by bendixsonnenberg** [comment]
it will be quite hard to make the Animation look good and also linus wants the site up afzer the weekend

**Comment by quannten24** [comment]
it will be quite hard to make the Animation look good and also linus wants the site up afzer the weekend

**Comment by christoph-fricke** [comment]
Moved it to the after release features... For now, no back animation
