### ISSUE TITLE
Js is a little bit f*cked up for the subsites...

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#42]
We are occuring problems light not workng ajax requests and css property errors... see console for informations

**Comment by bendixsonnenberg** [comment]
just ignore it 
its the magic line trying to find a place to go

**Comment by christoph-fricke** [comment]
Yeah but it looks stupid in the console and a major problem is that we are not able to generate a token and send the contact form!!! And that cant get ignored!!!
