### ISSUE TITLE
Need for E-Mail adress

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#46]
We still have to add a email adress in mail.php or the mail would get send in the unkown of the internet. We have to ask Linus for one. I am just creating this issue so we do not forget to do it.

**Comment by bendixsonnenberg** [comment]
[Flyer Sponsoren.pdf](https://github.com/christoph-fricke/shpioneers.de/files/853396/Flyer.Sponsoren.pdf)
page 2
