### ISSUE TITLE
Height for news card is to small on mobile.

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#47]
The is not enough space in the news card when it is extended. We should find a better solution to fit every text they throw at us...
![screenshot_2017-03-19-18-25-31](https://cloud.githubusercontent.com/assets/23103835/24083128/cbe2f936-0cd1-11e7-817a-d6f6082f700a.png)

**Comment by bendixsonnenberg** [comment]
we could just not animate the on mobile

**Comment by bendixsonnenberg** [comment]
and use height auto
