### ISSUE TITLE
layout for content on achievments page

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#49]
like we talked about
i think you know better how to material design it

**Comment by christoph-fricke** [comment]
Added tge design however I am not displaying the content atm. Wasnt in the mood to figure out how your algo works. I will implement the full responsive layout later.

**Comment by bendixsonnenberg** [comment]
i will put in the content

**Comment by christoph-fricke** [comment]
Responsive done
