### ISSUE TITLE
Images do not really fit in the cards

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#59]
@quannten24 we have to do some work here... Would be a shame if logos etc are cut of...

**Comment by bendixsonnenberg** [comment]
maybe we should cut all the images to roughly the same format as jorina

**Comment by christoph-fricke** [comment]
But the problem also appears for the sponsor images...

**Comment by bendixsonnenberg** [comment]
the sponsor logos are not that problematic.
with them its almost impossible to fint them onto the page without leaving large areas white

**Comment by christoph-fricke** [comment]
926accd They fit now but maybe we should give them a little bit of margin so they are not clipping directly to the borders of each card...
