### ISSUE TITLE
headers cause sidescrolling on mobile

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#60]
@christoph-fricke 
![screen shot 2017-03-21 at 15 18 07](https://cloud.githubusercontent.com/assets/25992157/24151644/a1ec0a18-0e49-11e7-8683-db7f4ae63504.png)

**Comment by christoph-fricke** [comment]
Make them smaller on mobile... They won't break like they should do because they are a single word, so the only solution is to make them smaller.

**Comment by bendixsonnenberg** [comment]
bb217db solved it
