### ISSUE TITLE
More sizes for the favicon

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#63]
@christoph-fricke you've got the svg file and the knowledge of which sizes are necessary
whenever you've got time

**Comment by christoph-fricke** [comment]
Well the problem is... There are not really defined sizes that you need... We can go overboard and include 15 different sizes or we take 2-4...

**Comment by christoph-fricke** [comment]
This is our package http://realfavicongenerator.net/favicon_result?file_id=p1bbrlekr51bcc1r0du6f1bra12vl6#.WNLILTs1-Uk
