### ISSUE TITLE
Removed header images on subpages

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#69]
My dad also told me, like Linus already did, that the header images on the subapges are a little bit to much of the goods... I removed them in a experiemental branch (https://github.com/christoph-fricke/shpioneers.de/tree/removed-headerImages) and would do some more changes like:
* moving page title in the navbar
* move logo on mobil into the sidebar to get more space for the title

if we continue to push this branch.

**Comment by bendixsonnenberg** [comment]
if we replace the current logo with text with the other smaller logo there may be enough space.
we could also replace the hambureg menu with the small logo, but then we would have to think of something for the language

**Comment by christoph-fricke** [comment]
I think it would be more elegant to execute my last bullet point...

**Comment by bendixsonnenberg** [comment]
dont let me stop you
as far as i am concerned you are expert on Webdesign

**Comment by christoph-fricke** [comment]
While I was doing this, I got the idea about adding the option to choose the season you want to view in the navbar like it is done on the sponsor page. It dont think that it is possible with the backend right now, but it is an option we should think about.

**Comment by bendixsonnenberg** [comment]
it is quite easy.
just put up an example entry and i will add the automatic generating

**Comment by bendixsonnenberg** [comment]
i would also recommend to remove the hover effect on the subpages
it makes it seem as if you could actually do something there

**Comment by christoph-fricke** [comment]
They would actually be options then... Only the teampage would have no options

**Comment by bendixsonnenberg** [comment]
is that a problem?

**Comment by christoph-fricke** [comment]
no

**Comment by bendixsonnenberg** [comment]
should we remove the current page from the hamburger menu?
it looks like you can click it but then it just brings you back to the page where you already are.

**Comment by christoph-fricke** [comment]
I would leave it there...

**Comment by bendixsonnenberg** [comment]
then maybe we could Highlight it in some wayAm 25.03.2017 13:46 schrieb Christoph Fricke <notifications@github.com>:I would leave it there...

**Comment by christoph-fricke** [comment]
Right now the color for the links has a opacity  of .7... We could bump it up to .87 for the current page...

**Comment by bendixsonnenberg** [comment]
maybe even give it a bit darker background because it is a bit confusing right now

**Comment by christoph-fricke** [comment]
75d5bf0

**Comment by christoph-fricke** [comment]
I would say that if there are now bugs this should be ready to get pulled. Or do you have some other things?

**Comment by bendixsonnenberg** [comment]
create the request and i will review it
nothing that i would like to add anymore

**Comment by bendixsonnenberg** [comment]
although now that i thought about it linus wanted me to incororate the icon for the sponsors on the subpages 
do you have an idea where we could put them?

**Comment by christoph-fricke** [comment]
They could be in the navbar next to each name... And on mobile you would only see the icon next to the title and not in the sidebar.

**Comment by bendixsonnenberg** [comment]
maybe just put the icon on mobile since on desktop there is more information anyways

**Comment by christoph-fricke** [comment]
But the icons could be missleading since they are not all day used icons...

**Comment by bendixsonnenberg** [comment]
i did not mean to remove the text form mobile, i meant to do what you said, but only the mobile part

**Comment by christoph-fricke** [comment]
But why wont you use no icons on desktop since there is the space?

**Comment by bendixsonnenberg** [comment]
i think that would look a little bit out of place there
people are used to icns on mobile, but the desktop version would look a little bit to "crowded" with the icons

**Comment by christoph-fricke** [comment]
But the icons are not all day used icons... So people might not instandly know what they are for...

**Comment by bendixsonnenberg** [comment]
and where is that a problem?

**Comment by christoph-fricke** [comment]
It looks a little bit strange if there are icons in the sidebar and the language options in text. Only icons would look even stranger. And a icon next to the hamburger menu does also not look good... If we are adding them back again, I would only add them in the desktop version next to each option.

**Comment by bendixsonnenberg** [comment]
i dont want to add the icons in the nav-menu. i want to add one icon in the title on mobile.
what i dont want is to add icons on the desktop version

**Comment by christoph-fricke** [comment]
I dont know... It just feels stange to have an icon directly next to the hamburger menu...

**Comment by bendixsonnenberg** [comment]
lets just ignore it for now
