### ISSUE TITLE
www.shpioneers.de show the php file instead of the parsed content

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#74]

**Comment by christoph-fricke** [comment]
Apperently it did not solve the issue. This is the way how you do it, at least that is what the internet says. Linus should ask our web provider about full .htaccess, which I guess we have, and about acces for mod_rewrite... This is needed.

Source from: http://www.danielhagen.de/web/url-mit-oder-ohne-www.html

**Comment by bendixsonnenberg** [comment]
it seams to work now.
did you do anything?
if not maybe the server just needed a restart

**Comment by christoph-fricke** [comment]
Don't know... I did nothing except the commit above. Maybe I still had the old htaccess file cached when I was testing it back in the days... But I am not sure if you are even able to cache this file... Or a server restart was needed like you said... But why would he randomly restart the server...?

P.s. It is also working for me now.
