### ISSUE TITLE
Credits for work

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#75]
Would be nice to get some credits or something like this since I put quite alot of effort in the website too.
Thought about something like the links below at the bottom of the website but I am open for suggestions.
-  https://jsfiddle.net/ChristophFricke/znj7q08x/
- https://jsfiddle.net/ChristophFricke/zqjb7sjt/

**Comment by bendixsonnenberg** [comment]
i wouldnt use the one with the heart.
i think we could put it either
- besides
- above
the "© 2017, Pioneers"

**Comment by christoph-fricke** [comment]
My family said the same... Funny xD... Got the idea from github.

However I thing below the copyright is the easiest to implement especially for mobile view...
