### ISSUE TITLE
Our outgoing links are a vulnerability...

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#77]
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by bendixsonnenberg** [comment]
this would only be a problem if we had

1. sensitive user data
2. the oppertunity for users to post their own links

right now i think we can trust our sponsors or the f1inschools page that they are not trying to hurt us

**Comment by christoph-fricke** [comment]
That is what I was thinking to but I just wanted to inform you because it is something not many people think about...
