### ISSUE TITLE
people are stealing our work

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#78]
today i learnt that some person in the formula 1 in schools team is using our code for their computer science class
i think we should maybe add some kind of license to this repo so that we could potentially sue them

**Comment by christoph-fricke** [comment]
Who is doing this??? We are already saying that they are not allowed to do it... o.O We definitely have to do something about this...

**Comment by bendixsonnenberg** [comment]
i would not worry too much about this
they are just trying to get better marks
we could try to put some kind of "papertowns" in there so that they will have problems explaining it

**Comment by bendixsonnenberg** [comment]
this thread is useless for now
