### ISSUE TITLE
New credits design

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#82]
I think that the current credits are looking a little bit boring so I tried to come up with something a little bit more interesting... I added a coffee mug to the credits since the heart was not the way to go... Take a look here:
https://jsfiddle.net/ChristophFricke/1Ltrtvnb/

Would be nice to have your feedback

**Comment by bendixsonnenberg** [comment]
Itwould be nice if the "gimmick", i.e. coffee mug, was in some context to the content of the web page

**Comment by christoph-fricke** [comment]
I can only think about a speedometer for a think that would fit. Found this:
- https://materialdesignicons.com/icon/speedometer

I am not sure how well it would fit. Do you maybe have some other ideas?

**Comment by bendixsonnenberg** [comment]
i thought about this but i was not able to find a solution

**Comment by christoph-fricke** [comment]
So you would suggest the speedometer?

**Comment by bendixsonnenberg** [comment]
yes
