### ISSUE TITLE
Old f1 Website

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#83]
Valerie found a old website (https://f1pioneers.wordpress.com/) which is still using the f1 in front of your name... While I reconized that, I also reconized that your email adress is f1pioneers[at]gmx.de...

I do not how much of a problem that is but since you told me that you can get banned if you are using f1 in front of your name, I think it is something you should be aware about...

**Comment by bendixsonnenberg** [comment]
we kniw that but we forgot the password and email adress for the eordpree account

**Comment by bendixsonnenberg** [comment]
i cant spell on my phone

**Comment by christoph-fricke** [comment]
I see but it is also in front of the mail address, which is also displayed on the new website...

**Comment by bendixsonnenberg** [comment]
i will try to get him to change it but it is the one we gave all our sponsors so i see almost no chance that it will be changed

**Comment by christoph-fricke** [comment]
You could let this email redirect to the new one and then a would try to create one with your domain...

**Comment by bendixsonnenberg** [comment]
linus is quite stuborn about this
