### ISSUE TITLE
New color variantes

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#85]
Google released a tool to create your Material color palette. The also allow you to use your own values.

I calculated the darker versions of our colors and I would maybe add them together with some refactoring after we merged the Webinterface.

Our color palette: https://material.io/color/#!/?view.left=1&view.right=1&primary.color=EA5B10&secondary.color=00BFFC

**Comment by bendixsonnenberg** [comment]
good idea

**Comment by christoph-fricke** [comment]
I tried the values and they looked really ...red. So I suggest that we stick with the old values.
