### ISSUE TITLE
2nd place german championship

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#87]
hi @christoph-fricke we(pioneers) won the 2nd place and now we need some kind of notification on the website. since i wont be home till tomorrow evening it would be nice if we had some kibd of banner online asap.

**Comment by christoph-fricke** [comment]
I will implement it as soon as possible.

What do you think about the idea to have the banner at the bottom of the page and the user can remove it with a button... The same like many cookie info banners...?

Does 2nd place mean that you are taking part in the world finals? :)

**Comment by bendixsonnenberg** [comment]
yes it does and i like your ideaAm 13.05.2017 19:47 schrieb Christoph Fricke <notifications@github.com>:I will implement it as soon as possible.
What do you think about the idea to have the banner at the bottom of the page and the user can remove it with a button... The same like many cookie info banners...?
Does 2nd place mean that you are taking part in the world finals? :)
