### ISSUE TITLE
Website needs new content

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#88]
@quannten24 You should really tell Jorina that she should update the sponsors like they did on Facebook. I would be a little bit pissed off if I would be a sponsors and the website is not up to date with my profile... Some new news would also be nice to give the site more purpose.

**Comment by bendixsonnenberg** [comment]
i've got the text i will just have to translate itAm 14.05.2017 14:22 schrieb Christoph Fricke <notifications@github.com>:@quannten24 You should really tell Jorina that she should update the sponsors like they did on Facebook. I would be a little bit pissed off if I would be a sponsors and the website is not up to date with my profile... Some new news would also be nice to give the site more purpose.

**Comment by bendixsonnenberg** [comment]
the production server now has all the new content we have right now
