### ISSUE TITLE
image of the team on achievments page

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#89]
like the title says
jorina suggested this and i liked the idea
this is not the highest priority but i would like to make this happen by wednsday

**Comment by bendixsonnenberg** [comment]
the pictures will be uploaded as soon as i get them

**Comment by christoph-fricke** [comment]
Roger, Roger! 🤖 🤖

**Comment by bendixsonnenberg** [comment]
ba6604e
