### ISSUE TITLE
Access to manifest is forbidden

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#92]
Chrome can not access the manifest to read useful information for the browser since we do not allow access to json files... 
![unbenannt](https://cloud.githubusercontent.com/assets/23103835/26400984/f0531eaa-4083-11e7-874e-f37d191a85a6.PNG)

**Comment by bendixsonnenberg** [comment]
what does the manifest do ?

**Comment by christoph-fricke** [comment]
For us it only sets some icons for chrome etc. but you could do so much more with it... The file is required for everything if you would want to create progressive webapps...
