### ISSUE TITLE
Email list

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#93]
We want to send a Newsletter to an one who is interessted and we want them to be able to sign up on the website. 
I think we could add a page to the backend where the emails will be send. @christoph-fricke do you have another idea? 
We also have to create some sort of signup. For this i am open to suggestions

**Comment by christoph-fricke** [comment]
Let us use a database please... *Bagging for yes* I would recommend SQLite since I don't know if we have access to a MySQL or MariaDB... It is the easiest way to store the user mails... Other than that we have to decide whether we want to use a framework (which is kind of boring) and whether we want to send html 5 email or plain text emails...

BTW I don't know why email response it not working for me on GitHub... :(

**Comment by bendixsonnenberg** [comment]
I've never used sql together with php, but it would be the right way to do it
We will have to use mysql because that is installed on the server

**Comment by christoph-fricke** [comment]
SQL is quite easy.. Especially with the PDO driver... I did some hacky stuff and I have found out that the server support the pdo driver but only has mysql installed... But don't worry, I use mysql on my server too...

**Comment by bendixsonnenberg** [comment]
would be nice if you could explain it to me sometime.
I think it would be better if we let Jorina design the email and just provide her with a list of all the recipients.
I see problems, because we will be storing personal data and that could be something where we will have to be very carefull about security.
and there are legal concerns as well:
[https://www.datenschutzbeauftragter-info.de/fachbeitraege/newsletter-und-datenschutz/](https://www.datenschutzbeauftragter-info.de/fachbeitraege/newsletter-und-datenschutz/)

**Comment by christoph-fricke** [comment]
We should discuss it via TS... 🤣

**Comment by bendixsonnenberg** [comment]
we will do bilingual, so we need an extra attribute for language

**Comment by bendixsonnenberg** [comment]
i think the only things left to do are:
   - styling the unsubscribe and confirm pages
   - some kind of interface for actually sending the emails

am i missing something?.

**Comment by bendixsonnenberg** [comment]
as far as i understand we have to include something like this:

Datenschutzerklärung von shpioneers.de

Diese Applikation erhebt personenbezogene Daten von ihren Nutzern.
Verantwortliche Stelle und Eigentümer

SH Pioneers
Gymnasium Kronshagen zHd. Pioneers
Suchsdorfer Weg 24, Kronshagen

E-Mail-Adresse des Eigentümers: info@shpioneers.de
Arten der erhobenen Daten

Zu den Arten der bezogenen Daten, die diese Applikation entweder selbst oder über Dritte erhebt, gehören: Vorname, Nachname und E-Mail.

Die Erhebung weiterer personenbezogener Daten kann in anderen Teilen dieser Datenschutzerklärung oder in einem sich spezifisch auf das Thema Datenerhebung beziehenden Erläuterungstext beschrieben werden.
Die personenbezogenen Daten werden entweder vom Nutzer freiwillig zur Verfügung gestellt oder automatisch erhoben, wenn diese Applikation genutzt wird.
Soweit nichts anderes angegeben ist, dient der Einsatz von Cookies – bzw. anderer Tracking-Tools – durch die diese Applikation oder durch die Inhaber von Fremdleistungen, die diese Applikation nutzt, der Identifizierung von Nutzern sowie der Speicherung von deren Vorlieben, und zwar zu dem einzigen Zweck, um die vom Nutzer gewünschten Dienstleistungen zu erbringen.
Werden bestimmte personenbezogene Daten nicht zur Verfügung gestellt, so kann diese Applikation ihre Dienstleistungen möglicherweise nicht erbringen.

Der Nutzer übernimmt die Verantwortung für die personenbezogenen Daten Dritter, die über diese Applikation veröffentlicht oder geteilt werden, und erklärt, dass er zur Angabe bzw. Bekanntgabe besagter Daten berechtigt ist, womit die verantwortliche Stelle diesbezüglich von jeglicher Verantwortung befreit ist.
Methode und Ort der Datenverarbeitung
Verarbeitungsmethoden

Die verantwortliche Stelle verarbeitet die Nutzerdaten auf ordnungsgemäße Weise und ergreift angemessene Sicherheitsmaßnahmen, um den unbefugten Zugriff und die unbefugte Weiterleitung, Modifizierung oder Vernichtung von Daten zu vermeiden.
Die Datenverarbeitung wird mittels Computern oder IT-basierten Systemen durchgeführt, einem organisatorischen Verfahren und Modus folgend die strikt auf die angegebenen Zwecke abzielen. Neben der verantwortlichen Stelle wird möglicherweise auch bestimmten Kategorien von Verantwortlichen Zugriff auf die Daten gewährt, die an der Betreibung der Website beteiligt sind (Personalverwaltung, Vertrieb, Marketing, Recht, Systemadministratoren) oder externen Parteien (wie Fremdanbietern technischer Dienstleistungen, Zustellunternehmen, Hosting-Anbietern, IT-Unternehmen oder Kommunkationsagenturen), die, falls notwendig, vom Eigentümer als Auftragsverarbeiter eingesetzt werden. Eine aktuelle Liste dieser Beteiligten kann jederzeit von der verantwortlichen Stelle verlangt werden.
Ort

Die Daten werden am Betriebsort der verantwortlichen Stelle und an allen anderen Orten, an denen sich die mit der Datenverarbeitung beteiligten Parteien befinden, verarbeitet. Für weitere Informationen, kontaktieren Sie bitte die verantwortliche Stelle.
Speicherdauer

Die Daten werden so lange gespeichert, wie es für das Erbringen der vom Nutzer gewünschten Dienstleistungen notwendig ist oder für die in diesem Dokument aufgeführten Zwecke angegeben ist. Der Nutzer kann die verantwortliche Stelle jederzeit auffordern, die Daten zu sperren oder zu entfernen.
Nutzung der erhobenen Daten

Die Daten über den Nutzer werden erhoben, damit der Eigentümer die Dienstleistungen erbringen kann. Darüber hinaus werden Daten zu folgenden Zwecken erhoben: Kontaktieren des Nutzers.

Die personenbezogenen Daten, die zu den aufgeführten Zwecken verwendet werden, sind in den jeweiligen Abschnitten dieses Dokuments aufgeführt.
Ausführliche Angaben über die Verarbeitung personenbezogener Daten

Personenbezogene Daten werden zu folgenden Zwecken unter Inanspruchnahme folgender Dienstleistungen erhoben:

    Kontaktieren des Nutzers
    Kontaktformular (Diese Applikation)

    Durch Ausfüllen des Kontaktformulars mit ihren Daten autorisieren Nutzer diese Applikation, ihre Angaben zu verwenden, um auf Bitten nach Informationen, Angebote oder sonstige Anfragen, die in der Kopfzeile des Formulars angegeben sind, zu reagieren.

    Erhobene personenbezogene Daten: E-Mail, Nachname und Vorname.
    Mailingliste oder Newsletter (Diese Applikation)

    Durch Anmelden zur Mailingliste oder zum Newsletter wird die E-Mail-Adresse des Nutzers der Kontaktliste der Personen hinzugefügt, die möglicherweise E-Mail-Nachrichten mit gewerblichen oder verkaufsfördernden Informationen in Bezug auf diese Applikation erhalten. Darüber hinaus kann Ihre E-Mail-Adresse dieser Liste zugefügt werden, wenn Sie sich für diese Applikation angemeldet haben oder nachdem Sie einen Kauf vorgenommen haben.

    Erhobene personenbezogene Daten: E-Mail.

Weitere Informationen über die Erhebung und Verarbeitung von Daten
Rechtliche Maßnahmen

Die personenbezogenen Daten des Nutzers können von der verantwortlichen Stelle zu rechtlichen Zwecken in gerichtlichen Verfahren oder vor möglichen Klagen verwendet werden, die sich daraus ergeben, dass diese Applikation oder die dazugehörigen Dienste nicht ordnungsgemäß genutzt wurden.
Der Nutzer ist sich dessen bewusst, dass die verantwortliche Stelle von den Behörden zur Herausgabe von personenbezogenen Daten aufgefordert werden könnte.
Weitere Informationen über die personenbezogenen Daten des Nutzers

Neben den in dieser Datenschutzerklärung aufgeführten Informationen kann diese Applikation dem Nutzer auf Anfrage Informationen zusenden, die sich auf bestimmte Dienste oder die Erhebung und Verarbeitung personenbezogener Daten beziehen.
Systemprotokolle und Wartung

Diese Applikation und die Dienste von Drittanbietern können zu Betriebs- und Wartungszwecken Dateien sammeln, die die über diese Applikation stattfindende Interaktion aufzeichnen (Systemprotokolle), oder andere personenbezogene Daten (z. B. IP-Adresse) zu diesem Zweck verwenden.
Nicht in dieser Datenschutzerklärung enthaltene Informationen

Weitere Informationen über die Erhebung oder Verarbeitung von personenbezogenen Daten können jederzeit von der verantwortlichen Stelle über die angegebenen Kontaktangaben angefordert werden.
Rechte von Nutzern

Nutzer sind jederzeit berechtigt zu erfahren, ob ihre personenbezogenen Daten gespeichert wurden, und können die verantwortliche Stelle kontaktieren, um die Inhalte und Herkunft der gespeicherten Daten zu erfahren, ihre Richtigkeit zu überprüfen, ihre Ergänzung, Löschung, Aktualisierung, Berichtigung oder Umwandlung in ein anonymisiertes Format oder die Sperrung rechtswidrig gespeicherter Daten zu verlangen sowie ihre Verarbeitung aus rechtmäßigen Gründen abzulehnen. Entsprechende Anfragen sind an die verantwortliche Stelle unter Verwendung der oben aufgeführten Kontaktangaben zu senden.

Diese Applikation unterstützt keine Nicht-Verfolgen-Anfragen (do not track) durch Webbrowser.
Die Information, ob benutzte Drittanbieter das Nicht-Verfolgen Protokoll befolgen, entnehmen Sie bitte der Datenschutzerklärung für den jeweiligen Dienst.
Änderungen dieser Datenschutzerklärung

Die verantwortliche Stelle behält sich vor, jederzeit Änderungen an dieser Datenschutzerklärung vorzunehmen, indem sie ihre Nutzer auf dieser Seite entsprechend informiert. Nutzern wird daher nahe gelegt, diese Seite regelmäßig aufzurufen und dabei das am Seitenende angegebene Datum der letzten Änderung zu prüfen. Lehnt ein Nutzer eine Änderung der Datenschutzerklärung ab, so darf er diese Applikation nicht mehr nutzen und kann die verantwortliche Stelle auffordern, seine personenbezogenen Daten zu löschen. Soweit nichts anderes angegeben ist, gilt die jeweils aktuelle Datenschutzerklärung für alle personenbezogenen Daten, die die verantwortliche Stelle über einen Nutzer gespeichert hat.
Informationen über diese Datenschutzerklärung

Die verantwortliche Stelle ist für die Datenschutzerklärung verantwortlich, die ab den von Iubenda bereitgestellten Modulen beginnt und auf den Servern von Iubenda gehosted wird.
Begriffsbestimmungen und rechtliche Hinweise
Personenbezogene Daten (oder Daten)

Angaben über eine natürliche oder juristische Person, Institution oder Gesellschaft, die durch Bezug auf andere Angaben (einschließlich einer persönlichen Identifikationsnummer) – auch indirekt – bestimmt wird oder bestimmbar ist.
Nutzungsdaten

Informationen, die diese Applikation (oder Dienste Dritter, die diese Applikation in Anspruch nimmt), automatisch erhebt, z. B.: die IP-Adressen oder Domain-Namen der Computer von Nutzern, die diese Applikation verwenden, die URI-Adressen (Uniform Resource Identifier), die Zeit der Anfrage, die Methode, die für die Übersendung der Anfrage an den Server verwendet wurde, die Größe der empfangenen Antwort-Datei, der Zahlencode, der den Status der Server-Antwort anzeigt (erfolgreiches Ergebnis, Fehler etc.), das Herkunftsland, die Funktionen des vom Nutzer verwendeten Browsers und Betriebssystems, die diversen Zeitangaben pro Aufruf (z. B. wie viel Zeit auf jeder Seite der Anwendung verbracht wurde) und Angaben über den Pfad, dem innerhalb einer Anwendung gefolgt wurde, insbesondere die Reihenfolge der besuchten Seiten, sowie sonstige Informationen über das Betriebssystem des Geräts und/oder die IT-Umgebung des Nutzers.
Nutzer

Die diese Applikation verwendende Person, auf die sich die personenbezogenen Daten beziehen, und die entweder der Dateninhaber sein muss oder die vom Dateninhaber bevollmächtigt wurde.
Dateninhaber

Die juristische oder natürliche Person, auf die sich die personenbezogenen Daten beziehen.
Datenverarbeiter

Die natürliche oder juristische Person, öffentliche Verwaltung oder ein sonstiges Organ, eine sonstige Gesellschaft oder sonstige Organisation, die bzw. das von der verantwortlichen Stelle bevollmächtigt wurde, die personenbezogenen Daten gemäß dieser Datenschutzerklärung zu verarbeiten.
Verantwortliche Stelle (oder Eigentümer)

Die natürliche oder juristische Person, öffentliche Verwaltung oder ein sonstiges Organ, eine sonstige Gesellschaft oder sonstige Organisation mit dem Recht, möglicherweise gemeinsam mit einer weiteren verantwortlichen Stelle Entscheidungen über den Zweck und die Methoden der Verarbeitung von personenbezogenen Daten sowie die hierfür verwendeten Mittel zu treffen, einschließlich der Sicherheitsmaßnahmen bezüglich des sich auf diese Applikation beziehenden Betriebs und der Nutzung. Soweit nichts anderes angegeben ist, ist die verantwortliche Stelle die natürliche oder juristische Person, in deren Eigentum diese Applikation steht.
Diese Applikation

Das Hardware- oder Software-Tool, mit dem die personenbezogenen Daten des Nutzers erhoben werden.
Rechtlicher Hinweis

Hinweis für europäische Nutzer: Diese Datenschutzerklärung wurde unter Einhaltung der Anforderungen von Art. 10 der EG-Richtlinie Nr. 95/46/EC und gemäß den Bestimmungen der Richtlinie 2002/58/EG, überarbeitet durch Richtlinie 2009/136/EG, zum Thema Cookies verfasst.

In dieser Datenschutzerklärung geht es ausschließlich um diese Applikation.

**Comment by bendixsonnenberg** [comment]
For the sendToAll.php to work you need to send it a post request with the parameters
- subjectde
- subjecten
- messagede
- messageen
The message can be written in html, although​ if necessary the css has to be included. 
It would also be great if we could check wether any input is empty before sending, because i really dont want to send empty emails.

There also has to be a <br> at the end of the message, because there is no line break before the unsubscribe link

**Comment by christoph-fricke** [comment]
@quannten24 There might be a security problem in our addSubscriber.php... There is no token needed to execute the file. Attackers might not be able to get data when they try random hashes but they are able to execute the sql queries which might lead to performance problems in the database.
