### ISSUE TITLE
Radio clip on Website

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#97]
Do you have an idea on how to incorporate a radio clip on the website? (mp3)

**Comment by christoph-fricke** [comment]
JS Web Audio API

**Comment by christoph-fricke** [comment]
https://go.readly.com/magazines/545257e1daafd0341700001b/59494f1cc5f0640001759ddd/67

**Comment by bendixsonnenberg** [comment]
I cant open that link because i would have to sign up

**Comment by christoph-fricke** [comment]
@quannten24 found this little blog post... Should be helpful when we implement the audio clip...
http://alexkatz.me/posts/building-a-custom-html5-audio-player-with-javascript/

**Comment by bendixsonnenberg** [comment]
Since the competition is over, we won't update this repo anymore
